<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace GPBMetadata\Proto;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Define::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(
            '
´
proto/service.protoProtocolLibgoogle/protobuf/empty.proto2ß
Server>
Login.ProtocolLib.LoginRequest.ProtocolLib.LoginResponseU
GetAllPerformanceInfo.google.protobuf.Empty$.ProtocolLib.PerformanceInfoResponseB
	Broadcast.ProtocolLib.BroadcastMessage.google.protobuf.EmptyB
	Heartbeat.ProtocolLib.NodeInfo.ProtocolLib.HeartbeatResponseB8Z#github.com/blackjack200/protocollib prokits\\protocolbproto3'
        , true);

        static::$is_initialized = true;
    }
}

