<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/define.proto

namespace prokits\protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ProtocolLib.HeartbeatResponse</code>
 */
class HeartbeatResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .ProtocolLib.BroadcastMessage msg = 1;</code>
     */
    private $msg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\prokits\protocol\BroadcastMessage>|\Google\Protobuf\Internal\RepeatedField $msg
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Define::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .ProtocolLib.BroadcastMessage msg = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>repeated .ProtocolLib.BroadcastMessage msg = 1;</code>
     * @param array<\prokits\protocol\BroadcastMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMsg($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \prokits\protocol\BroadcastMessage::class);
        $this->msg = $arr;

        return $this;
    }

}

