<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/define.proto

namespace prokits\protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ProtocolLib.NodeInfo</code>
 */
class NodeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool canJoin = 1;</code>
     */
    protected $canJoin = false;
    /**
     * Generated from protobuf field <code>repeated string online_players = 2;</code>
     */
    private $online_players;
    /**
     * Generated from protobuf field <code>int32 max_online_players = 3;</code>
     */
    protected $max_online_players = 0;
    /**
     * Generated from protobuf field <code>.ProtocolLib.NodePerformanceInfo performance_info = 4;</code>
     */
    protected $performance_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $canJoin
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $online_players
     *     @type int $max_online_players
     *     @type \prokits\protocol\NodePerformanceInfo $performance_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Define::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool canJoin = 1;</code>
     * @return bool
     */
    public function getCanJoin()
    {
        return $this->canJoin;
    }

    /**
     * Generated from protobuf field <code>bool canJoin = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanJoin($var)
    {
        GPBUtil::checkBool($var);
        $this->canJoin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string online_players = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOnlinePlayers()
    {
        return $this->online_players;
    }

    /**
     * Generated from protobuf field <code>repeated string online_players = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOnlinePlayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->online_players = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_online_players = 3;</code>
     * @return int
     */
    public function getMaxOnlinePlayers()
    {
        return $this->max_online_players;
    }

    /**
     * Generated from protobuf field <code>int32 max_online_players = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxOnlinePlayers($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_online_players = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ProtocolLib.NodePerformanceInfo performance_info = 4;</code>
     * @return \prokits\protocol\NodePerformanceInfo|null
     */
    public function getPerformanceInfo()
    {
        return $this->performance_info;
    }

    public function hasPerformanceInfo()
    {
        return isset($this->performance_info);
    }

    public function clearPerformanceInfo()
    {
        unset($this->performance_info);
    }

    /**
     * Generated from protobuf field <code>.ProtocolLib.NodePerformanceInfo performance_info = 4;</code>
     * @param \prokits\protocol\NodePerformanceInfo $var
     * @return $this
     */
    public function setPerformanceInfo($var)
    {
        GPBUtil::checkMessage($var, \prokits\protocol\NodePerformanceInfo::class);
        $this->performance_info = $var;

        return $this;
    }

}

