<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/define.proto

namespace prokits\protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SelectServerResponse</code>
 */
class SelectServerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string target_node_id = 1;</code>
     */
    protected $target_node_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $target_node_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Define::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string target_node_id = 1;</code>
     * @return string
     */
    public function getTargetNodeId()
    {
        return isset($this->target_node_id) ? $this->target_node_id : '';
    }

    public function hasTargetNodeId()
    {
        return isset($this->target_node_id);
    }

    public function clearTargetNodeId()
    {
        unset($this->target_node_id);
    }

    /**
     * Generated from protobuf field <code>optional string target_node_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetNodeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_node_id = $var;

        return $this;
    }

}

