<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace prokits\protocol;

/**
 * Protobuf type <code>Tracker</code>
 */
interface TrackerInterface
{
    /**
     * Method <code>login</code>
     *
     * @param \prokits\protocol\LoginRequest $request
     * @return \prokits\protocol\LoginResponse
     */
    public function login(\prokits\protocol\LoginRequest $request);

    /**
     * Method <code>heartbeat</code>
     *
     * @param \prokits\protocol\NodeInfo $request
     * @return \prokits\protocol\HeartbeatResponse
     */
    public function heartbeat(\prokits\protocol\NodeInfo $request);

    /**
     * Method <code>getAllNodeInfo</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \prokits\protocol\NodeInfoResponse
     */
    public function getAllNodeInfo(\Google\Protobuf\GPBEmpty $request);

    /**
     * Method <code>broadcast</code>
     *
     * @param \prokits\protocol\BroadcastMessage $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function broadcast(\prokits\protocol\BroadcastMessage $request);

    /**
     * Method <code>select</code>
     *
     * @param \prokits\protocol\SelectServerRequest $request
     * @return \prokits\protocol\SelectServerResponse
     */
    public function select(\prokits\protocol\SelectServerRequest $request);

    /**
     * Method <code>quit</code>
     *
     * @param \prokits\protocol\QuitRequest $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function quit(\prokits\protocol\QuitRequest $request);

}

